<?php

/**
 * Class GenerateSamplePatientsCommand
 */
class GenerateSamplePatientsCommand extends CConsoleCommand
{
    /**
     * @var int
     */
    private $patient_count = 100;

    private $episode_limit = 3;
    private $event_limit = 8;
    /**
     * @var array
     */
    private $referenceData = array();

    /**
     * @return string
     */
    public function getHelp()
    {
        return 'Generates a list of sample patients and their related data';
    }

    /**
     * @param string[] $args
     */
    public function run($args)
    {
        if (!empty($args[0])) {
            $this->patient_count = (int)$args[0];
        }

        $this->makeReferenceData();

        /* @var CDbTransaction $transaction */
        $transaction = Yii::app()->db->beginTransaction();
        for ($p = 0; $p < $this->patient_count; ++$p) {
            $patient = $this->generatePatient();
        }

        $transaction->commit();
    }

    /**
     *
     */
    private function makeReferenceData()
    {
        $this->referenceData['EthnicGroup'] = EthnicGroup::model()->findAll();
        $this->referenceData['Country'] = Country::model()->findAll();
        $this->referenceData['AddressType'] = AddressType::model()->findAll();
        $this->referenceData['Firm'] = Firm::model()->findAll();
        $this->referenceData['EpisodeStatus'] = EpisodeStatus::model()->findAll();
        $this->referenceData['EventType'] = EventType::model()->findAll();
        $this->referenceData['first_name'] = $this->getFirstNames();
        $this->referenceData['last_name'] = $this->getLastNames();
        $this->referenceData['address1'] = $this->getAddressOnes();
        $this->referenceData['address2'] = $this->getAddressTwos();
        $this->referenceData['county'] = $this->getCounties();
        $this->referenceData['city'] = $this->getCities();
        $this->referenceData['title'] = $this->getTitles();
    }

    /**
     * @return Patient
     */
    private function generatePatient()
    {
        $patient = new Patient();
        $patient->contact_id = $this->generateContact()->id;

        // unique hos_num
        while (true) {
            $patient->hos_num = mt_rand(999999, 99999999);
            if (!Patient::model()->exists('hos_num = :hos_num', array('hos_num' => $patient->hos_num))) {
                break;
            }
        }

        $patient->nhs_num = $this->randomNhsNumber();
        $patient->dob = $this->randomDate('1920-01-01');
        $patient->gender = $this->randomGender();
        $patient->date_of_death = $this->randomDecision(0.2) ? $this->randomDate($patient->dob) : null;
        $patient->ethnic_group_id = $this->randomDecision(0.5) ? $this->randomEthnicGroup()->id : null;
        $patient->is_local = 1;

        // GP
        if ($this->randomDecision(0.5)) {
            $patient->gp_id = $this->generateGp()->id;
        }

        // Practice
        if ($this->randomDecision(0.5)) {
            $patient->practice_id = $this->generatePractice()->id;
        }

        $this->saveOrThrow($patient);
        print "Added Patient {$patient->id}: {$patient->contact->first_name} {$patient->contact->last_name}\r\n";

        for ($e = mt_rand(0, $this->episode_limit); $e < $this->episode_limit; ++$e) {
            $episode = $this->generateEpisode($patient);
        }

        return $patient;
    }

    /**
     * @param bool $nick_name
     * @param bool $title
     * @return Contact
     */
    private function generateContact($nick_name = false, $title = false)
    {
        $contact = new Contact();
        $contact->first_name = $this->randomFirstName();
        $contact->last_name = $this->randomLastName();
        $contact->primary_phone = mt_rand(99999999, 999999999);
        $contact->title = $title ? $this->randomTitle() : null;

        $this->saveOrThrow($contact);
        print "Added Contact {$contact->id}: {$contact->first_name} {$contact->last_name}\r\n";

        $this->generateAddress($contact->id);

        return $contact;
    }

    /**
     * @param $contact_id
     *
     * @return Address
     */
    private function generateAddress($contact_id)
    {
        $address = new Address();
        $address->contact_id = $contact_id;
        $address->address1 = $this->randomAddress1();
        $address->address2 = $this->randomAddress2();
        $address->city = $this->randomCity();
        $address->postcode = mt_rand(999, 9999);
        $address->county = $this->randomCounty();
        $address->country_id = $this->randomCountry()->id;
        $address->address_type_id = $this->randomAddressType()->id;

        $this->saveOrThrow($address);
        print "Added Address {$address->id}: {$address->address1} {$address->address2}\r\n";

        return $address;
    }

    /**
     * @return Gp
     */
    private function generateGp()
    {
        $gp = new Gp();
        $gp->obj_prof = 'G' . mt_rand(999, 999999);
        $gp->nat_id = 'G' . mt_rand(999, 999999);
        $gp->contact_id = $this->generateContact(false, true)->id;
        $this->saveOrThrow($gp);
        print "Added Gp {$gp->id}: {$gp->obj_prof}\r\n";

        return $gp;
    }

    /**
     * @return Practice
     */
    private function generatePractice()
    {
        $practice = new Practice();
        $practice->code = 'E' . mt_rand(999999, 9999999);
        $practice->phone = mt_rand(999999999999, 9999999999999);
        $practice->contact_id = $this->generateContact()->id;

        $this->saveOrThrow($practice);
        print "Added Practice {$practice->id}: {$practice->code}\r\n";

        return $practice;

    }

    /**
     * @param Patient $patient
     */
    private function generateEpisode($patient)
    {
        $episode = new Episode();
        $episode->patient_id = $patient->id;
        $episode->firm_id = $this->randomFirm()->id;
        $episode->start_date = $this->randomDate($patient->dob, $patient->date_of_death);
        $episode->status = $this->randomEpisodeStatus()->id;
        $episode->eye_id = $this->randomDecision(0.5) ? mt_rand(1, 3) : null;
        $episode->disorder_id = $episode->eye_id ? $this->randomOphthalmicDisorder()->id : null;

        $this->saveOrThrow($episode);
        print "Added Episode {$episode->id} for firm {$episode->firm->name}\r\n";

        for ($e = mt_rand(1, $this->event_limit); $e < $this->event_limit; ++$e) {
            $event = $this->generateEvent($episode);
        }

        return $episode;
    }

    /**
     * @param Episode $episode
     * @return Event
     */
    private function generateEvent($episode)
    {
        $event = new Event();
        $event->episode_id = $episode->id;
        $event_type = $this->randomEventType();
        $event->event_type_id = 27;//$event_type->id;
        $event->event_date = $this->randomDate($episode->patient->dob);

        $this->saveOrThrow($event);
        print "Added Event {$event->id}: {$event_type->name}\r\n";

        //switch ($event->event_type->name) {
        //    case 'Examination':
        $this->generateExaminationEvent($event);
        //        break;
        //}

        return $event;
    }

    /**
     * @param Event $event
     */
    private function generateExaminationEvent($event)
    {
        $history = new \OEModule\OphCiExamination\models\Element_OphCiExamination_History();
        $history->event_id = $event->id;
        $history->description = 'Some description';
        $this->saveOrThrow($history);
        print "Added Element_OphCiExamination_History {$history->id}: {$history->description}\r\n";

        $diagnosis_element = new \OEModule\OphCiExamination\models\Element_OphCiExamination_Diagnoses();
        $diagnosis_element->event_id = $event->id;
        $this->saveOrThrow($diagnosis_element);

        $diagnosis = new \OEModule\OphCiExamination\models\OphCiExamination_Diagnosis();
        $diagnosis->disorder_id = $this->randomOphthalmicDisorder()->id; //$this->randomDisorder()->id;
        $diagnosis->element_diagnoses_id = $diagnosis_element->id;
        $diagnosis->eye_id = mt_rand(1, 3);
        $this->saveOrThrow($diagnosis);
    }

    /**
     * @param BaseActiveRecordVersioned $model
     * @throws CDbException
     */
    private function saveOrThrow($model)
    {
        if (!$model->save()) {
            throw new CDbException('Error saving ' . get_class($model) . ': ' . print_r($model->getErrors(), true));
        }
    }

    /**
     * @return EthnicGroup
     */
    private function randomEthnicGroup()
    {
        return $this->randomRecord('EthnicGroup');
    }


    /**
     * @return Country
     */
    private function randomCountry()
    {
        return $this->randomRecord('Country');
    }

    /**
     * @return AddressType
     */
    private function randomAddressType()
    {
        return $this->randomRecord('AddressType');
    }

    /**
     * @return Firm
     */
    private function randomFirm()
    {
        return $this->randomRecord('Firm');
    }

    /**
     * @return EpisodeStatus
     */
    private function randomEpisodeStatus()
    {
        return $this->randomRecord('EpisodeStatus');
    }

    public function randomOphthalmicDisorder()
    {
        static $criteria = null;
        if ($criteria === null) {
            $criteria = new CDbCriteria();
            $criteria->addCondition('specialty_id = 109');
            $criteria->order = 'RAND()';
        }

        return Disorder::model()->find($criteria);
    }

    public function randomSystemicDisorder()
    {
        static $criteria = null;
        if ($criteria === null) {
            $criteria = new CDbCriteria();
            $criteria->addCondition('specialty_id IS NULL OR specialty_id !+ 109');
            $criteria->order = 'RAND()';
        }

        return Disorder::model()->find($criteria);
    }


    /**
     * @return Disorder
     * /
     * private function randomDisorder()
     * {
     * return $this->randomRecord('Disorder');
     * }*/

    /**
     * @return EventType
     */
    private function randomEventType()
    {
        return $this->randomRecord('EventType');
    }

    /**
     * @return string
     */
    private function randomFirstName()
    {
        return $this->randomRecord('first_name');
    }

    /**
     * @return string
     */
    private function randomLastName()
    {
        return $this->randomRecord('last_name');
    }

    private function randomAddress1()
    {
        return $this->randomRecord('address1');
    }

    private function randomAddress2()
    {
        return $this->randomRecord('address2');
    }

    private function randomCity()
    {
        return $this->randomRecord('city');
    }

    private function randomCounty()
    {
        return $this->randomRecord('county');
    }

    private function randomGender()
    {
        return $this->randomDecision(0.5) ? 'F' : 'M';
    }

    private function randomTitle()
    {
        return $this->randomRecord('title');
    }

    /**
     * @param $key
     * @return mixed
     */
    private function randomRecord($key)
    {
        return $this->referenceData[$key][array_rand($this->referenceData[$key])];
    }

    /**
     * @param $start_date
     * @param null $end_date
     * @return false|string
     */
    private function randomDate($start_date, $end_date = null)
    {
        $min = strtotime($start_date);
        $max = strtotime($end_date ?: date('Y-m-d H:i:s'));

        $val = mt_rand($min, $max);

        return date('Y-m-d H:i:s', $val);
    }

    /**
     * @param $min
     * @param $max
     * @return mixed
     */
    private function randomFloat($min, $max)
    {
        return ($min + lcg_value() * (abs($max - $min)));
    }

    /**
     * @param $weight
     * @return bool
     */
    private function randomDecision($weight)
    {
        return $this->randomFloat(0, 1) < $weight;
    }

    /**
     * @return bool|CDbDataReader|mixed|string
     */
    private function randomNhsNumber()
    {
        /* @var CdbCommand $command */
        static $command = null;
        if ($command === null) {
            $command = Yii::app()->db->createCommand('SELECT nextval("patient_cera_number")');
        }

        return $command->queryScalar();
    }

    private function getFirstNames()
    {
        return array(
            'A',
            'A K',
            'Abigail',
            'Abraham',
            'Abram',
            'Adam',
            'Addison',
            'Adesola Omotara',
            'Adie',
            'Admin',
            'Agatha',
            'Agnes',
            'Alan',
            'Alec',
            'Alexander',
            'Alexandra',
            'Alexanger Graham',
            'Alexis',
            'Ali',
            'Alice',
            'Alison',
            'Allison',
            'Amber',
            'Amelia',
            'Amit',
            'Amrit',
            'Amy',
            'Andrea',
            'Andrew',
            'Aneurin',
            'Angela',
            'Angelina',
            'Anna',
            'Annabel',
            'Anne',
            'Annie',
            'Archibald',
            'Arnold',
            'Arthur',
            'Ashiq',
            'Ashley',
            'Ashton',
            'Aubrey',
            'Audrey',
            'Auriel',
            'Autumn',
            'Ava',
            'Avery',
            'Barbara',
            'Barnes',
            'Bartholomew',
            'Basil',
            'Beata',
            'Belinda',
            'Bernadine',
            'Bertha',
            'Bertram',
            'Bessie',
            'Bethany',
            'Bette',
            'Bette Davis',
            'Betty',
            'Bihari              ',
            'Bille',
            'Blanche',
            'Bobby',
            'Braden',
            'Brandon',
            'Brenda',
            'Bret',
            'Brett',
            'Brgitte',
            'Brianna',
            'Bridget',
            'Buddhi',
            'C',
            'Caden',
            'Cadence',
            'Carl',
            'Caroline',
            'Caroline H',
            'Carolyn',
            'Cataract',
            'Catherine',
            'Cecilia',
            'Chance',
            'Charis',
            'Charles',
            'Charlotte',
            'Chay',
            'Chet',
            'Chibogu',
            'Christopher',
            'Chuck',
            'Clive',
            'Coral',
            'Cowden',
            'Craig',
            'Cristalyn',
            'D',
            'D L',
            'Danute',
            'Darby',
            'Darlene',
            'Darnell',
            'DarryL',
            'David',
            'Deb',
            'Debbie',
            'Deborah',
            'Deirdre',
            'Demi',
            'Denise',
            'Dennis',
            'Derek',
            'Destiny',
            'Diamond',
            'Diana',
            'Dineshkumar',
            'Donald',
            'Doreen',
            'Dorian',
            'Dorothy',
            'Earl',
            'Edgar Allan',
            'Edith',
            'Edmund',
            'Edna',
            'Edward',
            'Edwin',
            'Edwina',
            'Eileen',
            'Elaine',
            'Elizabeth',
            'Ellen',
            'Elvis',
            'Emily',
            'Emma',
            'Emmeline',
            'Emory',
            'Enid',
            'Enoch',
            'Eric',
            'Eva',
            'Fang',
            'Farida',
            'Felicity',
            'Feve',
            'Florence',
            'Floyd',
            'Frank',
            'Franklin',
            'Fred',
            'Frederick',
            'Friedrich',
            'Gabriel',
            'Galileo',
            'Gautama',
            'Gazzard',
            'Genghis',
            'George',
            'Georgiana',
            'Gerald',
            'Gerard',
            'Germaine',
            'Gilbert',
            'Giles',
            'Gladys',
            'Gordon',
            'Grace',
            'Gregory',
            'Gurbachen',
            'Gurgen',
            'Guy',
            'Hannah',
            'Harriet',
            'Harrison',
            'Harry',
            'Hayden',
            'Hayley',
            'Hazel',
            'Helen',
            'Helton',
            'Henrietta',
            'Henry',
            'Hilary',
            'Hillary',
            'Holly',
            'Horatio',
            'Howard',
            'Hugh',
            'India',
            'Indira',
            'Ingrid',
            'Iris',
            'Isambard Kingdom',
            'J',
            'Jack',
            'Jacob',
            'Jacqueline',
            'Jade',
            'Jaden',
            'Jake',
            'Jakub',
            'James',
            'Jamilah',
            'Jane',
            'Jarmila',
            'Jean',
            'Jeffrey',
            'Jemma',
            'Jenna',
            'Jennifer',
            'Jenny',
            'Jenson',
            'Jerrold',
            'Jessica',
            'Jessie',
            'Jill',
            'Jing',
            'Joan',
            'Joanna',
            'Joanne',
            'Jocelyn',
            'Johann',
            'John',
            'Jonathan',
            'Jorge',
            'Joseph',
            'Joseph (Jr.)',
            'Josephine',
            'Joyce',
            'Julia',
            'Julian',
            'Julie',
            'Julio J',
            'June',
            'Juniper',
            'Justin',
            'Justine',
            'K',
            'K L',
            'Kailasben',
            'Kanchan',
            'Kate',
            'Katherine',
            'Kathleen',
            'Kathryn',
            'Katie',
            'Katie Mary',
            'Kayla',
            'Kazeem',
            'Keaton',
            'Ken',
            'Kendra',
            'Kenneth',
            'Kerr',
            'Kimball',
            'Kimberly',
            'Kirsten',
            'Kit',
            'Kitty',
            'Kofi',
            'Konstantinos',
            'Kristen',
            'Kylie',
            'Laura',
            'Lawrence',
            'Lee',
            'Leonora',
            'Lillian',
            'Linda',
            'Lindsay',
            'Lisa',
            'Liza',
            'Lizzie',
            'Louise',
            'Lucinda',
            'Lucretia',
            'Lucy',
            'M J',
            'M P',
            'Mabel',
            'Mackenzie',
            'Maddox',
            'Madeleine',
            'Madeline',
            'Mae',
            'Maggie',
            'Malcolm',
            'Mallory',
            'Marc',
            'Marcia',
            'Marcus',
            'Margaret',
            'Marianne',
            'Marie',
            'Marion',
            'Mark',
            'Marla',
            'Marlene',
            'Martha',
            'Mary',
            'Mata',
            'Matilda',
            'Matthew',
            'Maud',
            'Maude',
            'Maximilian',
            'Maxwell',
            'Meena',
            'Melanie',
            'Melinda',
            'Melissa',
            'Melville',
            'Meredith',
            'Michael',
            'Michaela',
            'Michelle',
            'Mildred',
            'Miles',
            'Miley',
            'Millicent',
            'Mindy',
            'Mohammed',
            'Moira',
            'Molly',
            'Mona',
            'Morgan',
            'Mort',
            'Mumtaz',
            'Muriel',
            'Myles',
            'Myron',
            'N',
            'Nancy',
            'Naomi',
            'Narme',
            'Nathanael',
            'Nelson',
            'Nevaeh',
            'Nevan',
            'Nicholas',
            'Nicolas',
            'Nicolaus',
            'Nicole',
            'Nigel',
            'Nikola',
            'Nikolaos D',
            'Noel',
            'Nora',
            'Norris',
            'O W',
            'Olajumoke',
            'Oliver',
            'Olivia',
            'Oprah',
            'Oscar',
            'Ottilie',
            'Ottiwell',
            'Otto',
            'P',
            'Paige',
            'Pamela',
            'Pamela Lilian',
            'Pascal',
            'Patricia',
            'Patrick',
            'Patsy',
            'Paul',
            'Paula',
            'Pauline',
            'Pearl',
            'Penelope',
            'Percy',
            'Pete',
            'Peter',
            'Philip',
            'Philippa',
            'Pippa',
            'Poppy',
            'Priscilla',
            'Pyotr Illyich',
            'Quentin',
            'R',
            'Rachel',
            'Raisa',
            'Ralph',
            'Randall',
            'Randolph',
            'Ratna',
            'Rebecca',
            'Reginald',
            'Rex',
            'Reynold',
            'Rhoda',
            'Richard',
            'Riley',
            'Robert',
            'Robin',
            'Roderick',
            'Roger',
            'Ronald',
            'Rosa',
            'Rosaleen',
            'Rose',
            'Rosie',
            'Rowan',
            'Rowena',
            'Roxanne',
            'Ruby',
            'Rukshmani',
            'Rupert',
            'Ruth',
            'Ryan',
            'S',
            'S M',
            'S Urgery',
            'Sally',
            'Sam',
            'Samantha',
            'Samuel',
            'Sandra',
            'Santiago',
            'Savannah',
            'Scarlett',
            'Schuyler',
            'Scott',
            'Selina',
            'Shahnaz',
            'Shanmugasundaram',
            'Shannon',
            'Sharon',
            'Sheba',
            'Sheila',
            'Sheryl',
            'Siddika',
            'Sidney',
            'Sigmund',
            'Simon',
            'Simone',
            'Siobhán',
            'Sophia',
            'Souheila',
            'Stacey',
            'Stafford',
            'Stella',
            'Stephen',
            'Steve',
            'Stockwell Group',
            'Sue',
            'Susan',
            'Suzanne',
            'Sybil',
            'Sydney',
            'Sylvia',
            'Tabitha',
            'Tamara',
            'Tammy',
            'Tania',
            'Tara',
            'Tarsem',
            'Teresa',
            'Tess',
            'Tessa',
            'Thelma',
            'Theodora',
            'Theodore',
            'Thomas',
            'Thomasina',
            'Timothy',
            'Tobias',
            'Toby',
            'Tracy',
            'Tristan',
            'Tyler',
            'Ulysses',
            'Valerie',
            'Vanessa',
            'Vicary',
            'Victor',
            'Victoria',
            'Vincent',
            'Violet',
            'Virginia',
            'W J',
            'Warren',
            'Wendy',
            'Whitney',
            'Wilfred',
            'Wilhelmina',
            'William',
            'Winston',
            'Wolfgang Amadeus',
            'Woodrow',
            'Y K',
            'Yoko',
            'Yosief',
            'Yuri',
            'Zsa Zsa',
        );
        /*
        $first_names = array();
        foreach (Yii::app()->db->createCommand('SELECT DISTINCT first_name FROM contact')->queryAll() as $row) {
            $first_names[] = $row['first_name'];
        }
        */
    }

    private function getLastNames()
    {
        return array(
            'Aarons',
            'Aaronson',
            'Abbot',
            'Abbott',
            'Abercrombie',
            'Ablett',
            'Acker',
            'Ackerman',
            'Acland',
            'Acres',
            'Adams',
            'Adatia',
            'Adepegba',
            'Adjei- Bediako',
            'Adlam',
            'Admin',
            'Aghion',
            'Aikin',
            'Ainscough',
            'Ainsworth',
            'Aird',
            'Alberts',
            'Albertson',
            'Alcock',
            'Alder',
            'Aldous',
            'Aldridge',
            'Alington',
            'Alio',
            'Allam',
            'Alleine',
            'Allerton',
            'Allman',
            'Alsop',
            'Alston',
            'Andrews',
            'Ang',
            'Antoinette',
            'Anyaegbunam',
            'Appleby',
            'Appleyard',
            'Apps',
            'Arif',
            'Arkwright',
            'Armistead',
            'Armstead',
            'Arnold',
            'Artham',
            'Ash',
            'Ashcroft',
            'Ashe',
            'Ashford',
            'Ashman',
            'Astbury',
            'Astill',
            'At',
            'Atkin',
            'Atkins',
            'Atkinson',
            'Aubrey',
            'Audley',
            'Austen',
            'Ayriss',
            'Ayrton',
            'Babington',
            'Bach',
            'Backhouse',
            'Baden-Powell',
            'Baggins',
            'Bagnold',
            'Bahadur',
            'Baines',
            'Balakanthan',
            'Barclay',
            'Bardot',
            'Barefoot',
            'Barford',
            'Barlow',
            'Barnhill',
            'Barrett',
            'Barron',
            'Barry',
            'Bates',
            'Bateson',
            'Baum',
            'Bayley',
            'Baynes',
            'Bean',
            'Beardsley',
            'Beauchamp',
            'Beaupre',
            'Beazley',
            'Beck',
            'Beckford',
            'Beckham',
            'Beddoes',
            'Bedingfield',
            'Beecher Stowe',
            'Beerbohm',
            'Beethoven',
            'Belcher',
            'Bell',
            'Bellamy',
            'Bellos',
            'Benjamin',
            'Benn',
            'Bennet',
            'Bennett',
            'Benson',
            'Bent',
            'Benton',
            'Bergman',
            'Bessie',
            'Bestor',
            'Bevan',
            'Bevins',
            'Bewley',
            'Bhan',
            'Bickerton',
            'Biernacki',
            'Bigg',
            'Bigge',
            'Biggs',
            'Billingham',
            'Birchall',
            'Birkin',
            'Blackwood',
            'Blake',
            'Blakemore',
            'Blakey',
            'Blanchflower',
            'Bland',
            'Blann',
            'Blatchford',
            'Blenkinsop',
            'Bloodsworth',
            'Bloor',
            'Blow',
            'Bloxsom',
            'Blyton',
            'Boakye-Duah',
            'Boatwright',
            'Boddy',
            'Bogart',
            'Boleyn',
            'Boocock',
            'Booth',
            'Borrow',
            'Bosanquet',
            'Bottomley',
            'Bourchier',
            'Bourne',
            'Bowden',
            'Bowie',
            'Bowker',
            'Bowlby',
            'Bowra',
            'Brackett',
            'Bradley',
            'Brailsford',
            'Bramwell',
            'Branch',
            'Brand',
            'Brandis',
            'Brandon',
            'Bray',
            'Brayshaw',
            'Brearley',
            'Breckenridge',
            'Breedlove',
            'Brent',
            'Brett',
            'Brewer',
            'Brickman',
            'Bridgeman',
            'Bridges',
            'Bridgman',
            'Brierley',
            'Briggs',
            'Brightman',
            'Bristow',
            'Broadbent',
            'Brock',
            'Brockett',
            'Brockman',
            'Broderick',
            'Brodhead',
            'Brodrick',
            'Brome',
            'Bromley',
            'Bronte',
            'Brook',
            'Brooke',
            'Brooker',
            'Brookes',
            'Brooks',
            'Broom',
            'Broome',
            'Broomhall',
            'Broughton',
            'Brown',
            'Brunel',
            'Brush',
            'Bryant',
            'Bryden',
            'Bryson',
            'Buckmaster',
            'Buddha',
            'Buffington',
            'Bugden',
            'Bull',
            'Bullard',
            'Bullock',
            'Bullokar',
            'Bulwer-Lytton',
            'Burdine',
            'Burgess',
            'Burkitt',
            'Burnaby',
            'Burns',
            'Burroughs',
            'Bush',
            'Bushell',
            'Buswell',
            'Butler',
            'Butt',
            'Butterfield',
            'Butterworth',
            'Buxton',
            'Byrd',
            'Cahoon',
            'Calbraith',
            'Calvert',
            'Camp',
            'Campion',
            'Canham',
            'Cann',
            'Cannan',
            'Caradoc',
            'Cardew',
            'Carlile',
            'Carlisle',
            'Carlson',
            'Carpenter',
            'Carrier',
            'Carrington',
            'Cass',
            'Cassie',
            'Catchpole',
            'Cates',
            'Catherwood',
            'Catt',
            'Catterall',
            'Catto',
            'Cavendish-Bentinck',
            'Caves',
            'Cawley',
            'Chadwick',
            'Chalioulias',
            'Chance',
            'Chandler',
            'Chaney',
            'Channing',
            'Chaplin',
            'Chapman',
            'Chapron',
            'Charles',
            'Charlesworth',
            'Chatto',
            'Chaucer',
            'Chavasse',
            'Chaytor',
            'Cheek',
            'Cheney',
            'Chengappa',
            'Child',
            'Childe',
            'Childs',
            'Chiles',
            'Chilton',
            'Chilvers',
            'Chinn',
            'Chorley',
            'Chowdhury',
            'Christie',
            'Christmas',
            'Chudasama',
            'Church',
            'Churchill',
            'Clapp',
            'Clark',
            'Clarke',
            'Clarkson',
            'Clavering',
            'Cleary',
            'Clemons',
            'Clerical',
            'Cliff',
            'Clinton',
            'Clitherow',
            'Close',
            'Clowes',
            'Coast',
            'Coates',
            'Cobbe',
            'Cobbett',
            'Cobbold',
            'Cobbs',
            'Cobby',
            'Coburn',
            'Cock',
            'Cockayne',
            'Cockerell',
            'Cockerill',
            'Cocks',
            'Codling',
            'Coffin',
            'Cole',
            'Coleclough',
            'Colegrove',
            'Coleman',
            'Coleridge',
            'Coles',
            'Coley',
            'Collingwood',
            'Collins',
            'Columbus',
            'Colvile',
            'Colville',
            'Colvin',
            'Compton',
            'Conant',
            'Condict',
            'Conrad',
            'Cook',
            'Cooke',
            'Cooksley',
            'Cooper',
            'Cope',
            'Copernicus',
            'Copley',
            'Cornwell',
            'Cory',
            'Cotes',
            'Cotton',
            'Cottrell',
            'Coulson',
            'Courtney',
            'Cowell',
            'Cowley',
            'Cowper',
            'Cox-Ertugrul',
            'Coxe',
            'Crabtree',
            'Craik',
            'Cree',
            'Cresswell',
            'Creswell',
            'Crick',
            'Crisp',
            'Croasdale',
            'Croft',
            'Crofts',
            'Cromwell',
            'Croom',
            'Crosland',
            'Cross',
            'Crosse',
            'Crouch',
            'Croucher',
            'Crow',
            'Crowe',
            'Cruger',
            'Cruwys',
            'Culbertson',
            'Culley',
            'Culliford',
            'Cumberland',
            'Cundy',
            'Curie',
            'Curtis',
            'Curzon',
            'Cussons',
            'Dade',
            'Daley',
            'Dalton',
            'Daniel',
            'Daniels',
            'Darby',
            'Darnell',
            'Darwin',
            'Davidson',
            'Davis',
            'Davison',
            'Dawkins',
            'Day-Lewis',
            'De Morgan',
            'Deal',
            'DeGeneres',
            'Demo User',
            'Denham',
            'Denman',
            'Dennett',
            'Dent',
            'Depala',
            'Derrick',
            'Dickens',
            'Dickinson',
            'Dietrich',
            'Digpal',
            'Dimbleby',
            'Doku',
            'Doolin',
            'Doshi',
            'Dr',
            'Drewe',
            'Droney',
            'Duchess of Cambridge',
            'Duerden',
            'Dulku',
            'Dunn',
            'Dutta',
            'Earhart',
            'Ebelthite',
            'Edison',
            'Edwards',
            'Edwardson',
            'Elbow',
            'Elderton',
            'Emmett',
            'Eyob',
            'F',
            'Fajgenbaum',
            'Farrington',
            'Faruqui',
            'Fawkes',
            'Fellows',
            'Fernandes Ramos',
            'Ferrer',
            'Fettiplace',
            'Fisher',
            'Fitz',
            'FitzGerald',
            'Fitzhugh',
            'Fitzsimons',
            'Flack',
            'Flanagan',
            'Flemming',
            'Foakes',
            'Frank',
            'Freud',
            'Fullilove',
            'Furse',
            'Gabbard',
            'Gabor',
            'Galilei',
            'Galton',
            'Gandhi',
            'Gentner',
            'Georgakarakos',
            'George',
            'Georgoulas',
            'Gibbs',
            'Gibson',
            'Gilbert',
            'Gilbertson',
            'Giles',
            'Glasby',
            'Godinho',
            'Golden',
            'Golding',
            'Gorbachev',
            'Gordon',
            'Gorelick',
            'Grainger',
            'Granger',
            'Grant',
            'Green',
            'Greer',
            'Grover',
            'Gudhka',
            'Gupta',
            'Haddad',
            'Haley',
            'Hall',
            'Hallows',
            'Hamilton',
            'Hampson',
            'Hampton',
            'Hansom',
            'Haq',
            'Hardy',
            'Hari',
            'Haring',
            'Harman',
            'Harris',
            'Harrison',
            'Harriss',
        );

        /*
        $last_names = array();
        foreach (Yii::app()->db->createCommand('SELECT DISTINCT last_name FROM contact')->queryAll() as $row) {
            $last_names[] = $row['last_name'];
        }*/
    }

    private function getTitles()
    {
        return array(
            'Captain',
            'Dr',
            'Dr1',
            'HRH',
            'Lady',
            'Lord',
            'Mdme',
            'Miss',
            'Mr',
            'Mrs',
            'Ms',
            'Mst',
            'Sir',
            'System',
        );
    }

    private function getAddressOnes()
    {
        return array(
            '1 City Road',
            '1 The street',
            '1, Barnhill Street',
            '1, Cawley Road',
            '1, Codling Court',
            '1, Daniels Street',
            '1, Scroggs Street',
            '10 Maypole Buildings',
            '10 Ridge Road',
            '10, Strickland Crescent',
            '100 Main Road',
            '100, Cock Street',
            '100, Darby Road',
            '100, Whately Road',
            '101, Bramwell Lane',
            '101, Coleridge Lane',
            '101, Flack Street',
            '101, Harman Crescent',
            '101, Wakeham Street',
            '101, Webbe Lane',
            '102, Bateson Crescent',
            '102, Bickerton Crescent',
            '102, Boatwright Road',
            '102, Cotes Avenue',
            '103, Abbott Avenue',
            '103, Bland Court',
            '103, Catterall Court',
            '103, Harriss Lane',
            '103, Purcell Lane',
            '103, Strickland Road',
            '104, Allfrey Avenue',
            '104, Broderick Crescent',
            '104, Teagarden Street',
            '105, Bugden Lane',
            '105, Carpenter Crescent',
            '105, Clinton Road',
            '105, Cobbett Road',
            '105, Holliday Lane',
            '105, Philipson Crescent',
            '105, Smollett Court',
            '105, Wright Court',
            '106, Cavendish Road',
            '106, Coleridge Court',
            '106, Crosland Court',
            '106, Cruwys Street',
            '106, Reynell Street',
            '106, Shelton Road',
            '106, Willcocks Road',
            '107, Cockayne Lane',
            '107, Elder Court',
            '107, F Street',
            '107, Rudman Street',
            '108, Atkins Avenue',
            '108, Close Lane',
            '108, Courtney Crescent',
            '108, Hayday Road',
            '108, Mayall Court',
            '108, Meyers Road',
            '108, Teagarden Avenue',
            '109, Ash Crescent',
            '109, Bagnold Street',
            '109, Beckham Road',
            '109, Brandon Street',
            '109, Chance Court',
            '109, Hogge Court',
            '109, Peace Street',
            '11, Beaufort Lane',
            '11, Fellows Avenue',
            '11, Meyers Lane',
            '11, Nordell Crescent',
            '11, Randell Crescent',
            '110 Grove Avenue',
            '110, Butterworth Lane',
            '110, Cliff Crescent',
            '110, Hawkins Street',
            '110, Maitland Road',
            '110, Maye Avenue',
            '110, Philbrook Lane',
            '110, Wheatley Lane',
            '111 Kenmore Avenue',
            '111, Catt Road',
            '111, Cheek Avenue',
            '111, Paterson Street',
            '112, Blakey Lane',
            '112, Bottomley Street',
            '112, Browning Road',
            '112, Charles Street',
            '112, Coxon Street',
            '112, Jones Lane',
            '112, Thompson Road',
            '112, Wells Lane',
            '113, Bellos Road',
            '113, Butler Crescent',
            '113, Stapleton Crescent',
            '114, Bottomley Road',
            '115, Alleine Crescent',
            '115, Beckford Avenue',
            '115, Cardew Lane',
            '116, Benton Road',
            '116, Bourne Avenue',
            '116, Clapp Court',
            '116, Clowes Road',
            '116, Miles Road',
            '117, Birchall Lane',
            '117, Boddy Court',
            '117, Bowlby Road',
            '117, Brayshaw Road',
            '117, Bryant Crescent',
            '117, Clarkson Crescent',
            '117, Copley Lane',
            '117, Hawkins Street',
            '117, Templer Avenue',
            '118, Bridgeman Street',
            '118, Crowe Avenue',
            '118, Deal Lane',
            '118, Richardson Road',
            '118, Sexton Court',
            '119, Aitchison Court',
            '119, Bloor Crescent',
            '119, Bristow Lane',
            '119, Pike Street',
            '12 Kings Farm Avenue',
            '12 Thornton Side',
            '12, Cockerill Avenue',
            '12, Cocks Crescent',
            '12, Croom Lane',
            '120, Boddy Street',
            '120, Bullock Court',
            '120, Catt Lane',
            '120, Cobbett Avenue',
            '120, Crick Avenue',
            '124 St. Georges Road',
            '128 Albert Road',
            '13 Grayham Rd',
            '13 Lisa Close',
            '13, Pennington Road',
            '13, Wells Street',
            '131 Cambridge Road',
            '135 Hicks Avenue',
            '139 Lillie Road',
            '14 Eton Rd',
            '14, Bennett Lane',
            '14, Bestor Court',
            '143-145 Balham Hill',
            '15, Baynes Avenue',
            '15, Bennet Avenue',
            '15, Bessie Avenue',
            '15, Close Road',
            '15, Day-Lewis Crescent',
            '16 Cruden Road',
            '16 Wricklemarsh Road',
            '16, Bennet Lane',
            '16, Davidson Court',
            '162 CITY ROAD',
            '17, Copley Road',
            '17, Jacobson Lane',
            '17, Janes Court',
            '17, Peterson Lane',
            '17, Sharpe Street',
            '18, Alder Road',
            '18, Brooker Crescent',
            '18, Denman Road',
            '18, Willman Road',
            '181 Boleyn Road',
            '19, Channing Lane',
            '19, Yallop Court',
            '199a Worsley Bridge Road',
            '2 Deanhill Road',
            '2 First Avenue',
            '2 Grosvenor Road',
            '2 South Way',
            '2 Southborough Road',
            '2, Brent Court',
            '2, Burns Crescent',
            '2, Norman Street',
            '2, Tidwell Street',
            '20 Crowland Walk',
            '20 Lyveden Road',
            '20 Newland Street',
            '20 Regan Way',
            '20 Taylor Avenue',
            '20, Appleyard Road',
            '20, Chorley Court',
            '20, Croasdale Crescent',
            '20, Davison Street',
            '20, Harriss Street',
            '20, Maitland Court',
            '20, Poulter Crescent',
            '20, Scrope Road',
            '20, Thurlow Court',
            '21 Empress Drive',
            '21 Upton Rd',
            '21, Cole Street',
            '21, Golding Court',
            '21, Hoby Crescent',
            '210 Uxbridge Road',
            '22, Ashford Road',
            '22, Blenkinsop Street',
            '23, Abbott Street',
            '23, Alden Road',
            '23, Barford Street',
            '23, F Lane',
            '23, Kendal Crescent',
            '24 Peticoat Lane',
            '24, Brooke Street',
            '24, Jerrold Crescent',
            '24, Ruddy Court',
            '24, Woolford Crescent',
            '25, Daley Crescent',
            '25, Fellows Court',
            '25, Laycock Avenue',
            '25, Ovenden Road',
            '25, Poulter Lane',
            '26 Gravel Road',
            '26, Ainscough Avenue',
            '26, Alder Lane',
            '26, Illidge Road',
            '26, Langtry Street',
            '26, Reynolds Court',
            '26, Roane Lane',
            '26, Savidge Lane',
            '26, Stephenson Lane',
            '26, Thomas Crescent',
            '263 Gander Green Lane',
            '266 Lea Bridge Road',
            '27 Dale Close',
            '27 The Greenway',
            '27, Coffin Road',
            '27, Davis Road',
            '27a-27e Stoke Newington Road',
            '28, Acland Avenue',
            '28, Campion Crescent',
            '28, Johnson Crescent',
            '29, Broome Crescent',
            '29, Charnock Crescent',
            '29, Drewe Lane',
            '29, Savidge Street',
            '298 Cavendish Road',
            '3 Duchy Drive',
            '3, Atkinson Crescent',
            '3, Bulmer Crescent',
            '3, Cavendish-Bentinck Road',
            '3, Chatto Road',
            '3, Galton Crescent',
            '3, Granger Crescent',
            '3, Norton Crescent',
            '30, Thompson Road',
            '303 Bath Road',
            '31 Morland Road',
            '31 Prentis Road',
            '31, Blackwood Court',
            '31, Cliff Crescent',
            '31, Coxon Street',
            '31, Crisp Road',
            '31, Hawkins Court',
            '31, Mead Lane',
            '31, Scroggs Lane',
            '32 Carpenter Way',
            '32 Deanhill Rd',
            '32 Maxwell Drive',
            '32, Ainsworth Street',
            '32, Bullokar Crescent',
            '32, Camp Court',
            '32, Cottrell Lane',
            '32, Olmsted Crescent',
            '32, Welles Crescent',
            '32, Wood Crescent',
            '33, Calvert Crescent',
            '33, Cockerell Court',
            '33, Nelson Lane',
            '33, Tibbetts Crescent',
            '34, Abbot Street',
            '34, Acland Lane',
            '34, Chaplin Court',
            '34, Emory Street',
            '34, Haring Avenue',
            '34, Harman Road',
            '34, Hughes Lane',
            '35, Appleyard Road',
            '35, Bourchier Lane',
            '35, Brayshaw Road',
            '35, Foakes Avenue',
            '35, Robison Lane',
            '35, Scrope Road',
            '35a High Street',
            '36, Aarons Court',
            '36, Burns Street',
            '36, Denham Crescent',
            '36, Giles Court',
            '36, Simpson Lane',
            '36, Smallcombe Street',
            '37, Arkwright Crescent',
            '37, Baddeley Court',
            '37, Beaufort Street',
            '37, Canham Crescent',
            '37, Penney Court',
            '37, White Street',
            '38, Fellows Avenue',
            '38, Jacobson Avenue',
            '38, Josephson Street',
            '38, Olmsted Street',
            '382 Upminster Road North',
            '39 Elgin Avenue',
            '39, Aghion Crescent',
            '39, Sprat Avenue',
            '4 Hawkwood Crescent',
            '4, Bushell Crescent',
            '4, Mobbs Lane',
            '4, Wilkinson Lane',
            '40 Liberty Bridge Road, East Village',
            '40, Bevins Court',
            '40, Colville Court',
            '40, Farrington Lane',
            '401 Westborough Road',
            '41 Gifford Gardens',
            '41, Albertson Road',
            '41, Allam Road',
            '41, Booth Road',
            '41, Hardy Court',
            '41, Harriss Street',
            '41, Mosley Lane',
            '41, Roane Lane',
            '41, Segraves Lane',
            '41, York Crescent',
            '417 Ilford Lane',
            '42 Westminster Court',
            '42, Chatto Lane',
            '42, Smollett Court',
            '42, Spivey Road',
            '43, Ashe Lane',
            '43, Davison Street',
            '43, Leonard Avenue',
            '43, Maye Lane',
            '44 Granville Close',
            '44 Highlands Road',
            '44, Brown Lane',
            '44, Bulwer-Lytton Court',
            '44, Fettiplace Avenue',
            '44, Galton Crescent',
            '44, Sartorius Court',
            '44, Seymour Court',
            '45 Burwell Road',
            '45, Bent Lane',
            '45, Davidson Crescent',
            '45, Gentner Street',
            '46 & 45c South Parade',
            '46 Rabournmead Drive',
            '46 Southern Avenue',
            '46, Bellamy Street',
            '46, Coley Lane',
            '465 Cranbrook Road',
            '47 Merrilands Road',
            '47, Alleine Street',
            '47, Culliford Avenue',
            '47, Day-Lewis Court',
            '47, Furse Road',
            '47, Mobbs Lane',
            '47, Peterson Street',
            '47, Teagarden Lane',
            '48, Cardew Road',
            '48, Cree Avenue',
            '48, Scrope Avenue',
            '48, Wakeham Avenue',
            '48, Wragg Lane',
            '49, Alder Street',
            '49, Best Avenue',
            '49, Bestor Avenue',
            '49, Compton Avenue',
            '497 Barking Road',
            '5, Beckford Crescent',
            '5, Butler Road',
            '5, Codling Crescent',
            '5, Denman Road',
            '5, Skirrow Road',
            '5, Smallcombe Road',
            '5, Willett Lane',
            '50 Chatsworth Gardens',
            '50, Atkins Court',
            '50, Cocke Crescent',
            '50, Copley Road',
            '50, Dalton Road',
            '50, Ebelthite Lane',
            '50, Morris Avenue',
            '51 Camden Gardens',
            '51, Acres Street',
            '51, Colegrove Road',
            '51, Emmett Road',
            '51, Rhett Avenue',
            '51, Smollett Lane',
            '52, Alberts Lane',
            '52, Bennet Road',
            '52, Castle Court',
            '52, Denham Crescent',
            '52, Derrick Court',
            '52, Hepburn Avenue',
            '52, Neilson Court',
            '52, Pleydell-Bouverie Road',
            '52, Templer Lane',
            '53 Farley Road',
            '53 Glenham Drive',
            '53, Allam Road',
            '53, Appleby Crescent',
            '53, Beaupre Crescent',
            '53, Scantlebury Court',
            '53, Shayne Lane',
            '54 Westcombe Avenue',
            '54, Neilson Crescent',
            '54, Skirrow Road',
            '54, Teagarden Lane',
            '55 York Road',
            '55, Alberts Avenue',
            '55, Branum Street',
            '55, Brooker Crescent',
            '55, Colville Lane',
            '55, Fellows Avenue',
            '55, Morris Court',
            '55, Worsley Street',
            '56 Tonbridge House',
            '56, Abercrombie Avenue',
            '56, Astbury Lane',
            '56, Seymour Lane',
            '56, Ward Crescent',
            '57, Allfrey Road',
            '57, Brewer Court',
            '57, Chiles Court',
            '57, Chinn Avenue',
            '57, Cotes Crescent',
            '57, Crofts Avenue',
            '57, Wragg Court',
            '58, Buckmaster Street',
            '58, Close Road',
            '58, Compton Avenue',
            '58, Mallory Avenue',
            '58, Myers Court',
            '58, Whittingham Street',
            '59, Aird Avenue',
            '59, Blake Street',
            '59, Browning Crescent',
            '59, Wilkinson Street',
            '6 Cotman Gardens',
            '6 Maud Gardens, Maud Road',
            '6 Netherby Drive',
            '"6 St. Leonards Court',
            'St. Leonards Road"',
            '6, Hemingway Avenue',
            '6, Mallory Avenue',
            '6, Nelson Lane',
            '6, Richardson Street',
            '6, Samuelson Avenue',
            '60 East Crescent',
            '60, Aghion Street',
            '60, Ayrton Street',
            '60, Brickman Court',
            '60, Burgess Road',
            '60, Colvile Road',
            '60, Elderton Avenue',
            '60, Shelton Court',
            '61, Allerton Lane',
            '61, Appleton Street',
            '61, Chaplin Court',
            '61, Day-Lewis Avenue',
            '61, Haven Road',
            '61, Hepburn Court',
            '61, Hobbs Crescent',
            '61, Hueffer Lane',
            '61, Spenser Avenue',
            '61, Spivey Avenue',
            '62, Bristow Avenue',
            '62, Broughton Court',
            '62, Colvin Street',
            '62, Croft Lane',
            '62, Cruger Road',
            '62, Ferrer Avenue',
            '62, Woolgar Street',
            '620 Longbridge Road',
            '63, De Morgan Avenue',
            '63, Whately Lane',
            '64, Coles Court',
            '64, Cowper Street',
            '64, Mather Avenue',
            '64, Norton Court',
            '64, Teagarden Road',
            '65 Aldersbrook Road',
            '65 Sistova Road',
            '65, Ashford Lane',
            '65, Brodhead Avenue',
            '65, Talbott Court',
            '65, Wakeham Court',
            '65, Wilby Crescent',
            '66 Empress Avenue',
            '66 Hatherop Rd',
            '66, Baines Lane',
            '66, Beckham Avenue',
            '66, Bellos Lane',
            '66, Bestor Road',
            '67, Hawking Lane',
            '68 Moselle Avenue',
            '68, Ayrton Lane',
            '68, Buckmaster Lane',
            '68, Chaucer Crescent',
            '68, Grainger Crescent',
        );
    }

    private function getAddressTwos()
    {
        return array(
            '',
            ' Slough',
            '1 College Lawn',
            '123 The lane',
            '162 City Road',
            '20 Bridge Lane, Battersea',
            '200 Uxbridge Road',
            '30 Upper Fairfield Road',
            '32 Gisborne St',
            '33 Mayday Road',
            '39 Woodfield Lne, Ashtead',
            '516 Kenton Lane',
            '9 Mersey Place',
            'Aboyne',
            'Acton',
            'Akebar',
            'Aldbury',
            'Aldershot',
            'Aldringham',
            'Aldrington Road',
            'Althorne Way, Dagenham',
            'Alum Bay',
            'Amberley',
            'Annacloy',
            'Apartments all over Lond',
            'Ardington',
            'Aughton',
            'Awre',
            'Aylmerton',
            'Balham',
            'Ballachulish',
            'Ballater',
            'Ballyconnell',
            'Bamburgh',
            'Bancroft Road',
            'Bannockburn',
            'Banstead',
            'Barking',
            'Barkingside',
            'Barnes',
            'Barnet Road',
            'Barnsley',
            'Barrack Road',
            'Bath',
            'Battersea',
            'Beaulieu',
            'Beckenham',
            'Belchamp St Paul',
            'Belgravia',
            'Bellshill',
            'Belsay',
            'Bere Regis',
            'Berkhamsted',
            'Bettws Evan',
            'Bexley Heath',
            'Bicester',
            'Billericay',
            'Billingshurst',
            'Bilsthorpe, Newark',
            'Bishops Stortford',
            'Bispham',
            'Blackheath',
            'Blackshaw Road',
            'Blackshaw Road, Tooting',
            'Blagdon',
            'Blakeney',
            'Boot',
            'Borough Green',
            'Boscombe',
            'Bournheath',
            'Bowes Park',
            'Bowness-on-Windermere',
            'Bramfield',
            'Bray',
            'Brixton',
            'Broadford',
            'Broadstairs',
            'Bromley',
            'Buckland Newton',
            'Bullen Street',
            'Burnhope',
            'Burnopfield',
            'Burntwood',
            'Burry Port',
            'Burstwick',
            'Caerleon',
            'Calvine',
            'Cardiff',
            'Cathcart',
            'Chadderton',
            'Chalfont St.Peter',
            'Charminster',
            'Cheetham Hill',
            'Chelford',
            'Chelmsford',
            'Chingford',
            'Chipping Norton',
            'Church Knowle',
            'City Road',
            'Clacton-On-Sea',
            'Clapham',
            'Clapton',
            'Clay Cross',
            'Claygate',
            'Coalpit Heath',
            'Cockfosters',
            'Cockfosters, Barnet',
            'Colchester',
            'Colliers Wood',
            'Combe Hay',
            'Comber',
            'Comberbach',
            'Conwy',
            'Countywide',
            'Cranford',
            'Cranford Lane, Heston',
            'Crawford Lane',
            'Crazies Hill',
            'Creigau',
            'Crundale',
            'Cumbernauld',
            'Dagenham',
            'Darley Abbey',
            'Darlingscott',
            'Dartford',
            'Denbigh',
            'Denmead',
            'Derby',
            'Dirleton',
            'Diss',
            'Dorchester',
            'Dormington',
            'Dover',
            'Droitwich',
            'Dulas',
            'Dunmurry',
            'Eaglescliffe',
            'Easingwold',
            'East Chaldon',
            'East Coker',
            'East Croydon',
            'East Ham',
            'East Huntspill',
            'East Sheen',
            'Edgware',
            'Edmondsley',
            'Edmonton',
            'Effort Street',
            'Elland',
            'Elm Park, Hornchurch',
            'Elmore Street,',
            'Emsworth',
            'Enfield',
            'Enville',
            'Epsom',
            'Essex',
            'Etchingham',
            'Ethelbert Road',
            'Ewell',
            'Ewell, Epsom',
            'Feltham',
            'Finchley',
            'Fitzalan Road',
            'For Health',
            'Forest Gate',
            'Foxdale',
            'Framfield Road',
            'Frensham',
            'Fulham',
            'Gants Hill',
            'Gatehead',
            'Gilling West',
            'Glendale',
            'Golders Green',
            'Goodmayes',
            'Gorse Covert',
            'Grainthorpe',
            'Gravesend',
            'Grazeley',
            'Green Street Green',
            'Greenford',
            'Guildersfield Road',
            'Hackney',
            'Hail Weston',
            'Hailsham',
            'Halstead',
            'Hammersmith',
            'Hampstead',
            'Hampton',
            'Hampton Hill',
            'Hanwell',
            'Hare Hatch',
            'Harefield',
            'Haringey',
            'Harpenden',
            'Harrington',
            'Harrow',
            'Hatch End',
            'Hathern',
            'Havant',
            'Hayes',
            'Hendon',
            'Herstmonceux,hailsham',
            'High St',
            'Higham-on-the-Hill',
            'Hindon',
            'Hintlesham',
            'Hitchin',
            'Hockley',
            'Holt',
            'Honiton',
            'Horfield',
            'Horley',
            'Hornchurch',
            'Hornsey',
            'Horwich',
            'Hounslow',
            'Hoxton',
            'Huntingdon',
            'Hurn',
            'Hutton-le-Hole',
            'Hythe',
            'Ickleford',
            'Ightham',
            'Ilford',
            'Invergarry',
            'Isleworth',
            'Islington',
            'Keighley',
            'Kenton',
            'Kesgrave',
            'Kettering',
            'Killough',
            'Kingsclere',
            'Kingston Upon Thames',
            'Kingston-Upon-Thames',
            'Kingswood',
            'Kippen',
            'Kirk Michael',
            'Knaphill',
            'Lambton Rd',
            'Latheronwheel',
            'Lewis',
            'Leyton',
            'Leytonstone,london',
            'Lisbellaw',
            'Lisconnor',
            'Lisdoonvarna',
            'Llangain',
            'Llanidloes',
            'Llantwit Major',
            'Llanwern',
            'Lochcarron',
            'London',
            'Looe',
            'Loughborough',
            'Loughton',
            'Low Moor',
            'Lower Peover',
            'Lower Stondon',
            'Luton',
            'Lydden',
            'Lydney',
            'Lymington',
            'Lympstone',
            'Lytham St Annes',
            'Madeira Road',
            'Maida Vale',
            'Maidstone',
            'Manor Park',
            'Marden',
            'Marlborough',
            'Marple',
            'Marple Bridge',
            'Marsham',
            'Meigle',
            'Mendlesham',
            'Merstham',
            'Merton Park',
            'Micheldever',
            'Millisle',
            'Milton Keynes',
            'Minster Lovell',
            'Mitcham',
            'Mollison Way, Edgware',
            'Monks Eleigh',
            'Moorfields Eye Hospital',
            'Morden',
            'Moulsoe',
            'Moulton',
            'Mountsorrel',
            'Nantyglo',
            'Nazeing',
            'Neal Cl',
            'Nethy Bridge',
            'New Malden',
            'Newlyn',
            'Newtonmore',
            'Norbury',
            'North Cheam,sutton',
            'North Fambridge',
            'North Harrow',
            'North Newton',
            'Northborough',
            'Northolt',
            'Northop',
            'Northrepps',
            'Northwood',
            'Norwich',
            'Oakley',
            'Off Grove Street',
            'Off Morning Lane,hackney',
            'Ogbourne St George',
            'Olympic Park',
            'Orpington',
            'Oscroft',
            'Osterley',
            'Otford',
            'Oulton',
            'Over',
            'Owermoigne',
            'Oxenholme',
            'Oxford',
            'Padiham',
            'Padworth Common',
            'Paignton',
            'Parton',
            'Pendlebury',
            'Pennal',
            'Penycae',
            'Peppard Common',
            'Peterborough',
            'Petts Hill',
            'Piccadilly',
            'Pidley',
            'Pinchbeck',
            'Plaistow',
            'Plymouth',
            'Polegate',
            'Pontarddulais',
            'Port Erin',
            'Portglenone',
            'Potters Bar',
            'Poulner, Ringwood',
            'Powfoot',
            'Prestatyn',
            'Preston',
            'Putney',
            'Queen\'s Park',
            'Queens Park',
            'Raglan',
            'Rainham',
            'Ramsbottom',
            'Rattery',
            'Rayleigh',
            'Raynes Park',
            'Richmond',
            'Richmond-Upon-Thames',
            'Ringstead',
            'Ripley',
            'Rishton',
            'Riverstown',
            'Roche',
            'Roehampton',
            'Romford',
            'Rooskey',
            'Rotherham',
            'Rotherhithe',
            'Rowhook',
            'Rowsley',
            'Ruislip',
            'Salen',
            'Sandtoft',
            'Selsdon',
            'Seven Kings',
            'Sevenoaks',
            'Sheepwash',
            'Sheffield',
            'Shirley',
            'Skeabost Bridge',
            'Skelmersdale',
            'Sleaford',
            'Smithfield',
            'South Harrow',
            'South Kyme',
            'South Norwood',
            'South Ockendon',
            'South Woodford',
            'Southall',
            'Southampton',
            'Southgate',
            'Southville',
            'Spaxton',
            'St Ann\'s Road',
            'St John\'s Wood',
            'St.Albans',
            'Staplehurst',
            'Stevenage',
            'Stockport',
            'Stoke Newington',
            'Stonehaven',
            'Stowting',
            'Streatham',
            'Streatham Hill',
            'Streatley on Thames',
            'Stretton',
            'Styal',
            'Sunbury-on-Thames',
            'Sutton',
            'Sutton Cheney',
            'Sutton-in-Ashfield',
            'Sydney Street',
            'Tatenhill',
            'Tayinloan',
            'The Royal London Hospital, Whitechapel',
            'Thorney',
            'Thornton Heath',
            'Thornton Watlass',
            'Tillington',
            'Tipton',
            'Tong',
            'Tongham',
            'Tooting',
            'Torteual',
            'Totland Bay',
            'Trecastle',
            'Trimley St Martin',
            'Tring',
            'Turnberry',
            'Turton',
            'Twickenham',
            'Unstone',
            'Upney lane',
            'Upper Norwood',
            'Upwey',
            'Virginia Water',
            'Wadeford',
            'Walderton',
            'Walpole St Andrew',
            'Walthamstow',
            'Wandsworth',
            'Warsash',
            'Washford',
            'Watercolour',
            'Watford',
            'Watford Road',
            'Watton-At-Stone',
            'Wealdstone',
            'Welling',
            'Wellingborough',
            'Wellow',
            'Wells-next-the-Sea',
            'Welwyn Garden City',
            'Wembley',
            'Wenvoe',
            'Werrington,peterborough',
            'West Bridgford,nottingham',
            'West Ealing',
            'West Frome',
            'West Harrow',
            'West Kensington',
            'West Wimbledon',
            'Westbourne Estate',
            'Westhill',
            'Westhoughton',
            'Wheelerend Common',
            'Whetstone',
            'White Waltham',
            'Whitington',
            'Whitworth',
            'Wichenford',
            'Widdop',
            'Wimbledon',
            'Wimbledon Chase',
            'Wincle',
            'Wisbech',
            'Wood Green',
            'Worcester',
            'Worlds End',
            'Worsthorne',
            'Worthing',
            'Writtle Road',
            'Wyke',
            'Wyverstone',
            'Yoxford',
        );
    }

    private function getCounties()
    {
        return array(
            '.',
            'asdasd',
            'Avon',
            'Bedfordshire',
            'Berkshire',
            'Borders',
            'Buckinghamshire',
            'Cambridgeshire',
            'Central',
            'Cheshire',
            'Cleveland',
            'Clwyd',
            'Cornwall',
            'County Antrim',
            'County Armagh',
            'County Down',
            'County Fermanagh',
            'County Londonderry',
            'County Tyrone',
            'Cumbria',
            'Derbyshire',
            'Devon',
            'Dorset',
            'Dumfries and Galloway',
            'Durham',
            'Dyfed',
            'East Sussex',
            'Essex',
            'Fife',
            'Gidea Park',
            'Gloucestershire',
            'Grampian',
            'GREATER LONDON',
            'Greater Manchester',
            'Gwent',
            'Gwynedd County',
            'Hampshire',
            'Herefordshire',
            'Hertfordshire',
            'Herts',
            'Highlands and Islands',
            'Hounslow',
            'Humberside',
            'Isle of Wight',
            'Kent',
            'Lancashire',
            'Leicestershire',
            'Leyton',
            'Lincolnshire',
            'London',
            'Lothian',
            'Merseyside',
            'Mid Glamorgan',
            'Middlesex',
            'Middx',
            'Norfolk',
            'North Yorkshire',
            'Northamptonshire',
            'Northumberland',
            'Nottinghamshire',
            'Oxfordshire',
            'Powys',
            'Rutland',
            'Shropshire',
            'Somerset',
            'South Glamorgan',
            'South Yorkshire',
            'Staffordshire',
            'Strathclyde',
            'Suffolk',
            'Surrey',
            'Tayside',
            'Tyne and Wear',
            'VIC',
            'Warwickshire',
            'West Glamorgan',
            'West Midlands',
            'West Sussex',
            'West Yorkshire',
            'Wiltshire',
            'Worcester',
            'Worcestershire',
        );
    }


    private function getCities()
    {
        return array(
            'Abbotsley',
            'Acton',
            'Airth',
            'Aldbury',
            'Alderbury',
            'Aldershot',
            'Alford',
            'Alfriston',
            'Alne',
            'Alrewas',
            'Alston',
            'Altnagelvin',
            'Alveston',
            'Amberley',
            'Ammanford',
            'Angle',
            'Ardbeg',
            'Ardfern',
            'Ardmillan',
            'Armthorpe',
            'asdasd',
            'Ashburnham Place',
            'Ashorne',
            'Ashwater',
            'Atherton',
            'Auchinleck',
            'Aveley',
            'Ballachulish',
            'Ballingarry',
            'Barking',
            'Barnet',
            'Barnston',
            'Barrow-in-Furness',
            'Barton Le Clay',
            'Battersea',
            'Bawtry',
            'Beamish',
            'Beckenham',
            'Beckley',
            'Bedfordshire',
            'Bedminster',
            'Bedworth',
            'Beith',
            'Belcoo',
            'Benderloch',
            'Benson',
            'Berkeley',
            'Berkshire',
            'Bethersden',
            'Bexley',
            'Bickerstaffe',
            'Bigbury-on-Sea',
            'Billericay',
            'Binfield',
            'Birchington',
            'Birmingham Airport',
            'Blair Atholl',
            'Blanchland',
            'Blisland',
            'Bloomsbury',
            'Bolventor',
            'Bonnybridge',
            'Boosbeck',
            'Bootle',
            'Bourn',
            'Bournemouth',
            'Bournheath',
            'Bow',
            'Bowburn',
            'Bowness-on-Windermere',
            'Brampton',
            'Brandesburton',
            'Bray',
            'Bridge Of Earn',
            'Brighouse Bay',
            'Brightstone Bay',
            'Brightwell Baldwin',
            'Brodick',
            'Brora',
            'Broughton',
            'Brownhills',
            'Bruton',
            'Bryncrug',
            'Brynford',
            'Brynsiencyn',
            'Bubbenhall',
            'Buckhorn Weston',
            'Buckinghamshire',
            'Bucknell',
            'Bunbury',
            'Burford',
            'Burghfield Common',
            'Burlescombe',
            'Burnhope',
            'Burren',
            'Burton Agnes',
            'Bury St Edmunds',
            'Butley',
            'Butterleigh',
            'Cadoxton',
            'Caernarfon',
            'Cairndow',
            'Calveley',
            'Cambridgeshire',
            'Cambuslang',
            'Canterbury',
            'Cardross',
            'Carmichael',
            'Carterton',
            'Cashel',
            'Castlegregory',
            'Castletown',
            'Catterick',
            'Cawood',
            'Chaddleworth',
            'Chagford',
            'Charlestown',
            'Charlton',
            'Chathill',
            'Cheddar',
            'Cheddington',
            'Chelmsford',
            'Chelmsford, Essex',
            'Cheltenham',
            'Chew Magna',
            'Chilham',
            'Chilton',
            'Chingford',
            'Christian Malford',
            'Christmas Common',
            'Church Stretton',
            'Churcham',
            'Churchdown',
            'City Road',
            'Clacton on Sea',
            'Clavering',
            'Clayton',
            'Cleator',
            'Clifton',
            'Cloughmills',
            'Clwyd',
            'Cobh',
            'Colchester',
            'Coldstream',
            'Coleford',
            'Compton',
            'Compton Abdale',
            'Compton Martin',
            'Conington',
            'Conisbrough',
            'Coombe Dingle',
            'Countywide',
            'Cowdenbeath',
            'Craignure',
            'Crantock',
            'Cressage',
            'Crianlarich',
            'Cricklade',
            'Cricklewood',
            'Crook',
            'Croydon',
            'Cruden',
            'Cruden Bay',
            'Cummertrees',
            'Cutthorpe',
            'Dagenham',
            'Dalston',
            'Daventry',
            'Dedham',
            'Deeping St James',
            'Deeside',
            'Deptford, London',
            'Derbyshire',
            'Dervaig',
            'Desborough',
            'Devon',
            'Diptford',
            'Donisthorpe',
            'Dorridge',
            'Dorset',
            'Douglas',
            'Dover',
            'Downend',
            'Downside',
            'Dumbarton',
            'Dunbar',
            'Dunblane',
            'Dundrum',
            'Dunmurry',
            'Dunster',
            'Ealing',
            'Easington',
            'East Melbourne',
            'East Morden',
            'East Sheen',
            'East Sussex',
            'Eastcote',
            'Eastham',
            'Ebbesbourne Wake',
            'Edgcumbe',
            'Edgehill',
            'Edgware',
            'Edmonton',
            'Edzell',
            'Ellesmere Port',
            'Elsecar',
            'Emborough',
            'Emersons Green',
            'Emsworth',
            'Enfield',
            'Englefield Green',
            'Epping Green',
            'Epsom',
            'Erskine',
            'Erwarton',
            'Essex',
            'Etchingham',
            'Evie',
            'Exeter',
            'Exminster',
            'Farmborough',
            'Farnham',
            'Farrington Gurney',
            'Farthingstone',
            'Fawkham',
            'Feltham',
            'Fen Ditton',
            'Fenstanton',
            'Fenwick',
            'Flatford',
            'Flempton',
            'Fonthill Gifford',
            'Foolow',
            'Fordham',
            'Forest Gate',
            'Forres',
            'Fotheringhay',
            'Freuchie',
            'Frinton-On-Sea',
            'Fulham',
            'Galston',
            'Galway',
            'Gerrards Cross',
            'Glangarnock',
            'Glencoe',
            'Glendaruel',
            'Glenisla',
            'Glenshee',
            'Gloucestershire',
            'Glynneath',
            'Gorebridge',
            'Gorey',
            'Gourock',
            'Graves End',
            'Great Kingshill',
            'Great Tew',
            'Great Waltham',
            'Green Park',
            'Greenford',
            'Greet',
            'Guisborough',
            'Hailsham',
            'Hale',
            'Halwill Junction',
            'Hamble',
            'Hambrook',
            'Hampshire',
            'Hampstead',
            'Hampton',
            'Hanley',
            'Hannah Lane',
            'Hanwell',
            'Hardwick',
            'Harlington',
            'Harpenden',
            'Harpur Hill',
            'Harrogate',
            'Harrow',
            'Harrow, Middlesex',
            'Harvington',
            'Harwich',
            'Haselbury Plucknett',
            'Hassocks',
            'Havant',
            'Haydon Bridge',
            'Heald Green',
            'Heather',
            'Hebburn',
            'Heddon-on-the-Wall',
            'Hertfordshire',
            'Hertingfordbury',
            'Herts',
            'Hexton',
            'Heydon',
            'Heytesbury',
            'High Bickington',
            'High Roding',
            'Higham',
            'Higham Ferrers',
            'Highfield',
            'Hilderstone',
            'Hinckley',
            'Hinton Charterhouse',
            'Hinton St Mary',
            'Hitchin',
            'Hockley',
            'Hockley Heath',
            'Holbeach',
            'Holmesfield',
            'Holsworthy',
            'Holyhead',
            'Honiton',
            'Hornchurch',
            'Horndean',
            'Horsley Woodhouse',
            'Houghton Le Spring',
            'Hounslow',
            'Hounslow West',
            'Hubberholme',
            'Hull',
            'Hythe',
            'Ilford',
            'Ilford, Essex',
            'Ilkeston',
            'Ingatestone',
            'Ingbirchworth',
            'Ipswich',
            'Isle Of Man',
            'Isleworth',
            'Islington',
            'Islington,',
            'Ivinghoe',
            'Ivy Hatch',
            'Jesmond',
            'Kelly Brae',
            'Kelso',
            'Kelty',
            'Kempsey',
            'Kent',
            'Ketton',
            'Kilmacolm',
            'Kimbolton',
            'Kingscote',
            'Kingston',
            'Kingston Lisle',
            'Kingston Upon Thames',
            'Kingswood',
            'Kinloch Rannoch',
            'Kinlochleven',
            'Kirkconnel',
            'Knapdale',
            'Knowl Hill',
            'L',
            'Ladram Bay',
            'Laide',
            'Lamphey',
            'Lapland',
            'Laugharne',
            'Lavernock',
            'Leatherhead',
            'Leatherhead, Surrey',
            'Leckford',
            'Leeds Bradford Airport',
            'Leek Wootton',
            'Leicestershire',
            'Leysdown-on-Sea',
            'Lidgate',
            'Lincolnshire',
            'Linwood',
            'Lisbellaw',
            'Liss',
            'Litlington',
            'Little Hampden',
            'Little Snoring',
            'Littlehampton,west Sussex',
            'Liverpool Road, Luton',
            'Llancadle',
            'Llandwrog',
            'Llandysul',
            'Llangefni',
            'Llangynidr',
            'Llannerch-Y-Medd',
            'Llannon',
            'Llansamlet',
            'London',
            'Long Newton',
            'Longham',
            'Longridge',
            'Longtown',
            'Longueville',
            'Lorton',
            'Loughborough',
            'Lower Cwmtwrch',
            'Lower Fagley',
            'Lower Hartshay',
            'Lower Oddington',
            'Lower Peover',
            'Ludgvan',
            'Lupton',
            'Luss',
            'Luton',
            'Lydney',
            'Madley',
            'Maidencombe',
            'Maidenhead',
            'Maldon',
            'Marianglas',
            'Markfield',
            'Markyate',
            'Marlborough',
            'Marsh Benham',
            'Mealsgate',
            'Medmenham',
            'Mellor',
            'Mersea Island',
            'Merthyr Tydfil',
            'Middlesex',
            'Millbrook',
            'Milton Common',
            'Milton Ernest',
            'Minsterley',
            'Miserden',
            'Mitcham',
            'Mithian',
            'Mold',
            'Morar',
            'Morden',
            'Morpeth',
            'Mortimers Cross',
            'Morwenstow',
            'Moulton',
            'Muckamore',
            'N1',
            'Nelson',
            'Netherton',
            'New Malden',
            'New Mills',
            'New Southgate',
            'Newborough',
            'Newcastle Airport',
            'Newland',
            'Newnham',
            'Newport',
            'Newry',
            'Norfolk',
            'Normanton',
            'North Petherton',
            'Northamptonshire',
            'Northolt',
            'Northrepps',
            'Northwood',
            'Norton in Hales',
            'Notting Hill',
            'Nottinghamshire',
            'Oaklands Estate',
            'Ockley',
            'Old Knebworth',
            'Oldfield',
            'Orford',
            'Orpington, Kent',
            'Osmington',
            'Oswaldkirk',
            'Otterton',
            'Overton',
            'Oxfordshire',
            'Oxhill',
            'Paglesham',
            'Paignton',
            'Palnackie',
            'Pease Pottage',
            'Pensford',
            'Penzance',
            'Peppard Common',
            'Peterborough',
            'Peterlee',
            'Petham',
            'Pinner,middlesex',
            'Pitlochry',
            'Plumpton',
            'Port Charlotte',
            'Portknockie',
            'Portpatrick',
            'Portrush',
            'Potters Bar',
            'Powmill',
            'Primrose Hill',
            'Pulloxhill',
            'Purfleet',
            'Quainton',
            'Queensferry',
            'Rackenford',
            'Rainham',
            'Rayleigh',
            'Reay',
            'Redditch',
            'Redhill',
            'Resipole',
            'Rhos on Sea',
        );
    }
}
