<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:18.
 */
class PreviousOperationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PreviousOperation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        return;//Disabling non-functional tests
        $this->object = new PreviousOperation();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PreviousOperation::model
     *
     * @todo   Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers PreviousOperation::tableName
     *
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers PreviousOperation::rules
     *
     * @todo   Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers PreviousOperation::relations
     *
     * @todo   Implement testRelations().
     */
    public function testRelations()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers PreviousOperation::attributeLabels
     *
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers PreviousOperation::search
     *
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers PreviousOperation::getDateText
     *
     * @todo   Implement testGetDateText().
     */
    public function testGetDateText()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }
}
