<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:18.
 */
class ProtectedFileTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var ProtectedFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ProtectedFile();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ProtectedFile::createFromFile
     *
     * @todo   Implement testCreateFromFile().
     */
    public function testCreateFromFile()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::model
     *
     * @todo   Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::tableName
     *
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::rules
     *
     * @todo   Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::relations
     *
     * @todo   Implement testRelations().
     */
    public function testRelations()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::getBasePath
     *
     * @todo   Implement testGetBasePath().
     */
    public function testGetBasePath()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::getPath
     *
     * @todo   Implement testGetPath().
     */
    public function testGetPath()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::setSource
     *
     * @todo   Implement testSetSource().
     */
    public function testSetSource()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::hasThumbnail
     *
     * @todo   Implement testHasThumbnail().
     */
    public function testHasThumbnail()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers ProtectedFile::getThumbnail
     *
     * @todo   Implement testGetThumbnail().
     */
    public function testGetThumbnail()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }
}
