<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-10 at 11:10:19.
 */
class SettingMetadataTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SettingMetadata
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SettingMetadata();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SettingMetadata::model
     *
     * @todo   Implement testModel().
     */
    public function testModel()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers SettingMetadata::tableName
     *
     * @todo   Implement testTableName().
     */
    public function testTableName()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers SettingMetadata::rules
     *
     * @todo   Implement testRules().
     */
    public function testRules()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers SettingMetadata::relations
     *
     * @todo   Implement testRelations().
     */
    public function testRelations()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers SettingMetadata::attributeLabels
     *
     * @todo   Implement testAttributeLabels().
     */
    public function testAttributeLabels()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }

    /**
     * @covers SettingMetadata::search
     *
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // Remove the following lines when you implement this test.
        return;//Disabling non-implemented tests
    }
}
